=pod

=head1 Commentary

=head2 Development cycle and Group work

=over

We worked out most of our API in the initial sessions and mostly adhered to what we had planned between the top and middle layer


We were initially planning on keeping the quires in the Database layer but Gabriele working on the middle layer decided that he
would prefer to query the database directly from his layer so I ceased work on queries. This simplified the API development
on the database end as I simply provided Gabriele with the physical schema of my database so that he could write queries for 
it. 



=back

=head2 Challenges

=over



We hosted the database for our website on the Birkbeck servers, the limited permissions meant that I could not create a web-user account
with read only permissions to access the database.

=back

=head2 Things learned

=head3 git 

=over

I used git for the first time on this project and found it really useful, for working on the same code-base on different platforms. I
am still refining my use of this system, I have begun to develop some habits, but need to wok to continue committing with sufficient
frequency and increase fluency with which I can use the reverting to particular versions feature.

=back

=head3 POD - Plain Old Documentation

=over

I have learned to use POD Perl's in-line documentation markup language during this project. I found that this changed the way that I commented
code, because this markup needs to understandable out of the context provided by the code itself its tend to make it necessary to have more
redundant content in comments than is usual and I'm not sure about its impact of the readability of the code as it takes up a lot of space on
the monitor. however writing the documentation in-line did save a lot of duplication of work buy comparison with writing a whole separate 
documentation.

I had some trouble sorting out Pod2HTML to generate the documentation automatically

=back

=head3 Testing using test::more

=over

I learn to use some of the basic testing functionality in the test more module. We had already begun development before we covered 
test driven development which was a new concept to me but is an approach that I find very appealing in theory so would like to try 
it in practice. I found that is was quite difficult to develop test of some of the code I wrote for this project after the fact. 
I think test driven development would force me to think about error handling more during the development process as my basic approach
tends to assume the best case scenario that the data will match the expected format, and when it does not unanticipated things
can start happening. This was a particular challenge with the data for this project as many elements in the genbank file did not 
match the expected format


=back

=cut